### ISSUE TITLE
Not necessary beforeEach, please use before

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/6-starit-js-ui-automation-msalnikov#1]
https://github.com/StartITProtractorJS/6-starit-js-ui-automation-msalnikov/blob/47b0f8afce097a37533613593826af9539f879f7/tests/mainMenu-spec.ts#L4

Please use "before" statement, if you have only 1 test-case.

**Comment by msalnikov** [comment]
@alexanderpavlovets, fixed.
