### ISSUE TITLE
Please remember about selector chaining 

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/6-starit-js-ui-automation-msalnikov#2]
https://github.com/StartITProtractorJS/6-starit-js-ui-automation-msalnikov/blob/47b0f8afce097a37533613593826af9539f879f7/tests/createAccountForm-spec.ts#L11

It is possible to make selectors more readable by chaining 
```
const customerForm = $('form[name="customer_form"]')
const firstName = customerForm.$('[name="firstname"]')
```

**Comment by msalnikov** [comment]
This approach isn't always applicable. But thx for advice. I'll try to use it in future.
