### ISSUE TITLE
Performance and readability 

### ISSUE THREAD

**Issue by alexanderpavlovets** [StartITProtractorJS/6-starit-js-ui-automation-msalnikov#3]
https://github.com/StartITProtractorJS/6-starit-js-ui-automation-msalnikov/blob/47b0f8afce097a37533613593826af9539f879f7/tests/createAccountForm-spec.ts#L27

Nice one with template literal. 
Here performance is not critical, but why not to declare "random" once: 
```
const randomValue = Math.random().toString(36).slice(2)
```
And then use it with the template literal 
```
$(email).setValue(`${random}@email.com`);
```
This will allow: 
- call function only once (performance and stability)
- better debug possibilities. If you have 1 random value - it will create(pseudo-code): 
{
user: 123123123 User
email: 123123123 Account
description: 123123123 Descr
}
So if test fails, you are able to connect all the data by equal "random".

**Comment by msalnikov** [comment]
@alexanderpavlovets, got it, thanks for advice. Fixed.
